### PR TITLE
Smoother zoom

### PR DESCRIPTION
**Pull request by EDM115**
As requested here : https://github.com/Keksuccino/JustZoom/issues/2

### Changes :
**Deps**
- [x] Uses ForgeGradle 6+
- [x] Minecraft Forge 41.0.91 -> 41.1.0
- [x] Bump from Gradle 7.4.2 to 8.1.1

**Features**
- [x] Added a lerpAmount in the Config
- [x] Changed a bit the config (shows the default value)
- [x] Zooming is now smooth, we use a Lerp function to achieve this
- [x] Smoothing fully configurable (from 1 to 100 frames, default = 10)
- [x] Releasing the key makes the zoom out also being smooth

**Bugs**
- Releasing the zoom key have some weird behavior
- [x] https://github.com/EDM115/JustZoom/blob/169231b1db8e86c6332292c5e82e420f5525731c/src/main/java/de/keksuccino/justzoom/ZoomHandler.java#L67
- [x] If we compare it to any value under 1, we have a kind of "cinematic camera" going on
- [x] The lower the value, the easier we get that state
- [x] Spamming the zoom key twice gets us rid of it for some reason
- [x] Cached values like FOV and lerp are overwritten
- Comparing to 1 is the best bet to do now. But it have some caveats
- [x] There are some frames near the end where we get brutally back to default FOV (without any smoothing). The solution would be to set the comparison lower, but as stated above, it's buggy
- [x] If we scroll to get to a normal FOV, that weird state described above occurs. Zooming again removes it
- A potential fix would be to use a lerpAmount bigger, close to 1 as we get the comparison done from 1 to 0.5. Tho, I'm not sure if it works

### Build :
https://github.com/EDM115/JustZoom/releases/download/1.0.2/justzoom-1.0.2-OLD.jar

### CODE REVIEW

**Comment by EDM115** [comment]
I recommend not to merge until I fixed the bugs

**Comment by EDM115** [comment]
There's now a brutal comeback near the end when releasing the key  
Will be fixed later on  
  
Build : https://github.com/EDM115/JustZoom/releases/download/1.0.2/justzoom-1.0.2-HALF-FIXED.jar

**Comment by Keksuccino** [comment]
Thank you for taking the time to do this!
Will try to add it to all versions when the bugs are fixed!

**Comment by EDM115** [comment]
I still have school but the assignments are too boring 😂 at least i have some challenge here

**Comment by EDM115** [comment]
Was just a mistake.  
However, smoothCamera stays enabled if you hit the key very fast or if the FPS is low (< 30)  
  
Will attempt a fix

**Comment by EDM115** [comment]
Last bug : zooming backwards keeps the smoothCamera  
probably because we don't check if we go past that value (which shouldn't happen)

**Comment by Keksuccino** [comment]
Added in Just Zoom v1.0.2! Thank you again!

**Pull request closed without merging**
